### ISSUE TITLE
iNFC using TagMo assets in violation of its license

### ISSUE THREAD

**Issue by AbandonedCart** [strengthen/LeetCode#33]
I apologize if this repository is not directly associated with iNFC, but this is where the application redirects support. 

It would appear iNFC is using a significant likeness to TagMo's logo with similar functionality. This seems overly coincidental. Is there more to it?

iNFC:
![image](https://user-images.githubusercontent.com/1173913/225276701-03a86ff9-ace8-438c-bae2-397374118aaa.png)

TagMo:
![image](https://user-images.githubusercontent.com/1173913/225276903-a167f686-27ab-4745-96a4-5980fc49f610.png)

https://github.com/HiddenRamblings/TagMo/pull/116/

**Comment by strengthen** [comment]
All NFC products can use the NFC logo. It can be said that both iNFC and TagMo use the NFC logo. iNFC will be listed on the App Store on April 13, 2021. I have never downloaded and used TagMo.

**Comment by AbandonedCart** [comment]
Seems overly ironic for it to have the same amiibo functionality and, of all the logos out there, use the same one that was submitted for TagMo. Given the nature of some features in iNFC, it was important to clarify that TagMo was not aware of any connection between the two applications.

It's illegal to include the bin files in the application, since that is piracy. That is between you and Nintendo, though. That being said, TagMo does not take any responsibility for any code used outside the terms of its license and cannot be held responsible if it is used to perform illegal activities.

I'll take it as "just a coincidence" and leave it at that.
